### ISSUE TITLE
Issue creating Application yaml

### ISSUE THREAD

**Issue by timbroder** [mediapeers/ansible-role-newrelic-plugin-agent#1]
Configuration:

```
newrelic_plugins:
  - nginx:
    host: localhost
    port: 8080
    path: /status_page/
```

Expected in newrelic-plugin-agent.cfg:

```
  nginx:
    - host: localhost
      port: 80
      path: /nginx_stub_status
```

Actual in newrelic-plugin-agent.cfg:

```
  host: localhost
nginx: null
path: /nginx_stub_status
port: 80
```

It _looks_ like something similar to [this issue](https://github.com/ansible/ansible/issues/11189) but when I run the sample from that ticket, it's fine

Have you come across this? Thanks
